// <auto-generated />
using ApiSoftfinc.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace ApiSoftfinc.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180521125917_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Cls_Softfinc.Usuariosapi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Idusuario");

                    b.Property<string>("clave");

                    b.Property<string>("usuario");

                    b.HasKey("Id");

                    b.ToTable("Usuariosapis");
                });
#pragma warning restore 612, 618
        }
    }
}
